// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: add_user_to_organisation.sql

package models

import (
	"context"
)

const addUserToOrganisation = `-- name: AddUserToOrganisation :exec
INSERT INTO membership (user_id, org_id)
VALUES (
        "user id from request bosy",
        "organisation id from path variable"
    )
`

func (q *Queries) AddUserToOrganisation(ctx context.Context) error {
	_, err := q.db.Exec(ctx, addUserToOrganisation)
	return err
}
