// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: add_user_to_organisation.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToOrganisation = `-- name: AddUserToOrganisation :exec
INSERT INTO membership (user_id, org_id)
VALUES ($1, $2)
`

type AddUserToOrganisationParams struct {
	UserID pgtype.UUID
	OrgID  pgtype.UUID
}

// Adds a user to a particular organisation
func (q *Queries) AddUserToOrganisation(ctx context.Context, arg AddUserToOrganisationParams) error {
	_, err := q.db.Exec(ctx, addUserToOrganisation, arg.UserID, arg.OrgID)
	return err
}
