// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create_user.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (first_name, last_name, email, password, phone)
VALUES ($1, $2, $3, $4, $5) RETURNING user_id, first_name, last_name, email, password, phone
`

type CreateUserParams struct {
	FirstName string
	LastName  string
	Email     string
	Password  string
	Phone     pgtype.Text
}

// creates a new user and adds her to the user table
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Password,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
	)
	return i, err
}
