// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: create_organisation.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganisation = `-- name: CreateOrganisation :one
INSERT INTO organisation (name, description)
VALUES ($1, $2)
RETURNING org_id, name, description
`

type CreateOrganisationParams struct {
	Name        string
	Description pgtype.Text
}

// Creates an organisation and adds it to the organisation table
func (q *Queries) CreateOrganisation(ctx context.Context, arg CreateOrganisationParams) (Organisation, error) {
	row := q.db.QueryRow(ctx, createOrganisation, arg.Name, arg.Description)
	var i Organisation
	err := row.Scan(&i.OrgID, &i.Name, &i.Description)
	return i, err
}
