// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_user_if_in_same_organisation.sql

package models

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserIfInSameOrganisation = `-- name: GetUserIfInSameOrganisation :one
SELECT u.user_id,
    u.first_name,
    u.last_name,
    u.email,
    u.phone
FROM "user" u
    JOIN membership m1 ON u.user_id = m1.user_id
    JOIN membership m2 ON m1.org_id = m2.org_id
WHERE u.user_id = $1
    AND m2.user_id = $2
`

type GetUserIfInSameOrganisationParams struct {
	UserID   pgtype.UUID
	UserID_2 pgtype.UUID
}

type GetUserIfInSameOrganisationRow struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Phone     pgtype.Text
}

// Gets a user in same organisation with a particular user
func (q *Queries) GetUserIfInSameOrganisation(ctx context.Context, arg GetUserIfInSameOrganisationParams) (GetUserIfInSameOrganisationRow, error) {
	row := q.db.QueryRow(ctx, getUserIfInSameOrganisation, arg.UserID, arg.UserID_2)
	var i GetUserIfInSameOrganisationRow
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
	)
	return i, err
}
