// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: get_user.sql

package models

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, first_name, last_name, email, password, phone
FROM "user"
WHERE email = $1
`

// Gets a user
func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Password,
		&i.Phone,
	)
	return i, err
}
