// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Membership struct {
	UserID pgtype.UUID
	OrgID  pgtype.UUID
}

type Organisation struct {
	OrgID       pgtype.UUID
	Name        string
	Description pgtype.Text
}

type User struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	Email     string
	Password  string
	Phone     pgtype.Text
}
